"""user updates

Revision ID: 8c5a684a9a0a
Revises: caae651d784d
Create Date: 2022-12-09 15:54:59.905074

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8c5a684a9a0a'
down_revision = 'caae651d784d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_token')
        batch_op.drop_column('token_expiration')
        batch_op.drop_column('token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('token_expiration', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.create_index('ix_user_token', ['token'], unique=False)

    # ### end Alembic commands ###
