"""del_num_edition

Revision ID: 9a660a3c4680
Revises: 3da0bcc5e03e
Create Date: 2022-12-04 19:15:08.592403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a660a3c4680'
down_revision = '3da0bcc5e03e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edition', schema=None) as batch_op:
        batch_op.drop_column('num_edition')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_edition', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
