"""add_text_field

Revision ID: cf6d2bac65b0
Revises: 099c551f8626
Create Date: 2022-12-04 13:57:10.125896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf6d2bac65b0'
down_revision = '099c551f8626'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edition', schema=None) as batch_op:
        batch_op.drop_column('text')

    # ### end Alembic commands ###
